site_name: MicroJSON Documentation
site_author: Bengt Ljungquist
copyright: (c) 2023 PolusAI
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/languages/json.min.js
  - init_highlight.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/styles/default.min.css

markdown_extensions:
  - codehilite
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
nav:
  - Home: 'index.md'
  - Example: 'example.md'
  - Validation: 'validation.md'
