# generated by datamodel-codegen:
#   filename:  Geometry.json
#   timestamp: 2023-06-28T15:38:42+00:00
"""Microjson. Auto-generated by datamodel-codegen"""

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional, Union

from pydantic import BaseModel, Field


class Type68(Enum):
    point = 'Point'


class GeojsonGeometryItem(BaseModel):
    type: Type68
    coordinates: List[float] = Field(..., min_items=2)
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type69(Enum):
    line_string = 'LineString'


class Coordinate39(BaseModel):
    __root__: List[Any]


class GeojsonGeometryItem1(BaseModel):
    type: Type69
    coordinates: List[Coordinate39] = Field(..., min_items=2)
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type70(Enum):
    polygon = 'Polygon'


class Coordinate40(Coordinate39):
    pass


class GeojsonGeometryItem2(BaseModel):
    type: Type70
    coordinates: List[List[Coordinate40]]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type71(Enum):
    multi_point = 'MultiPoint'


class GeojsonGeometryItem3(BaseModel):
    type: Type71
    coordinates: List[List[float]]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type72(Enum):
    multi_line_string = 'MultiLineString'


class Coordinate41(Coordinate39):
    pass


class GeojsonGeometryItem4(BaseModel):
    type: Type72
    coordinates: List[List[Coordinate41]]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type73(Enum):
    multi_polygon = 'MultiPolygon'


class Coordinate42(Coordinate39):
    pass


class GeojsonGeometryItem5(BaseModel):
    type: Type73
    coordinates: List[List[List[Coordinate42]]]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class GeojsonGeometry(BaseModel):
    __root__: Union[
        GeojsonGeometryItem,
        GeojsonGeometryItem1,
        GeojsonGeometryItem2,
        GeojsonGeometryItem3,
        GeojsonGeometryItem4,
        GeojsonGeometryItem5,
    ] = Field(..., title='GeoJSON Geometry')
