# generated by datamodel-codegen:
#   filename:  LineString.json
#   timestamp: 2023-06-01T19:31:21+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field


class Type(Enum):
    line_string = 'LineString'


class Coordinate(BaseModel):
    __root__: List[Any]


class GeojsonLinestring(BaseModel):
    type: Type
    coordinates: List[Coordinate] = Field(..., min_items=2)
    bbox: Optional[List[float]] = Field(None, min_items=4)
