"""Microjson. Auto-generated by datamodel-codegen"""

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field


class Type89(Enum):
    multi_line_string = 'MultiLineString'


class Coordinate51(BaseModel):
    __root__: List[Any]


class GeojsonMultilinestring(BaseModel):
    type: Type89
    coordinates: List[List[Coordinate51]]
    bbox: Optional[List[float]] = Field(None, min_items=4)
