# generated by datamodel-codegen:
#   filename:  MultiPolygon.json
#   timestamp: 2023-06-01T19:31:21+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field


class Type(Enum):
    multi_polygon = 'MultiPolygon'


class Coordinate(BaseModel):
    __root__: List[Any]


class GeojsonMultipolygon(BaseModel):
    type: Type
    coordinates: List[List[List[Coordinate]]]
    bbox: Optional[List[float]] = Field(None, min_items=4)
