# generated by datamodel-codegen:
#   filename:  MultiPoint.json
#   timestamp: 2023-06-01T19:31:21+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Type(Enum):
    multi_point = 'MultiPoint'


class GeojsonMultipoint(BaseModel):
    type: Type
    coordinates: List[List[float]]
    bbox: Optional[List[float]] = Field(None, min_items=4)
