"""Microjson. Auto-generated by datamodel-codegen"""

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field


class Type43(Enum):
    multi_polygon = 'MultiPolygon'


class Coordinate25(BaseModel):
    __root__: List[Any]


class GeojsonMultipolygon(BaseModel):
    type: Type43
    coordinates: List[List[List[Coordinate25]]]
    bbox: Optional[List[float]] = Field(None, min_items=4)
