# generated by datamodel-codegen:
#   filename:  Point.json
#   timestamp: 2023-06-01T19:31:21+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Type(Enum):
    point = 'Point'


class GeojsonPoint(BaseModel):
    type: Type
    coordinates: List[float] = Field(..., min_items=2)
    bbox: Optional[List[float]] = Field(None, min_items=4)
