# generated by datamodel-codegen:
#   filename:  Polygon.json
#   timestamp: 2023-06-01T19:31:21+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field


class Type(Enum):
    polygon = 'Polygon'


class Coordinate(BaseModel):
    __root__: List[Any]


class GeojsonPolygon(BaseModel):
    type: Type
    coordinates: List[List[Coordinate]]
    bbox: Optional[List[float]] = Field(None, min_items=4)
